compressionLevel: mixed
enableGlobalCache: true
nodeLinker: node-modules
supportedArchitectures:
  cpu:
    - arm64
    - x64
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
